import {createClient} from "@supabase/supabase-js";import "./style.css";
const URL=import.meta.env.VITE_SUPABASE_URL,KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const app=document.querySelector("#app");const S={mode:"login",user:null,profile:null,company:null,section:"overview",msg:""};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const sb=URL&&KEY?createClient(URL,KEY):null;
function nav(id,icon,label){return `<button data-nav="${id}" class="${S.section===id?"active":""}"><span>${icon}</span>${label}</button>`}
function renderAuth(){app.innerHTML=`<div class="auth"><div class="auth-card"><div class="brand big">● YOUYOU</div><div class="tag">AI CUSTOMER AGENT</div><h1>${S.mode==="login"?"Welcome back.":"Build your AI agent."}</h1><p>Real authentication powered by Supabase.</p>${S.msg?`<div class="alert">${esc(S.msg)}</div>`:""}<form id="auth">${S.mode==="signup"?`<label>Full name<input name="full_name" required></label><label>Company name<input name="company_name" required></label>`:""}<label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="6" required></label><button class="primary"> ${S.mode==="login"?"Sign in":"Create account"} </button></form><button id="switch" class="link">${S.mode==="login"?"Create a new account":"Already have an account? Sign in"}</button></div></div>`;
document.querySelector("#switch").onclick=()=>{S.mode=S.mode==="login"?"signup":"login";S.msg="";renderAuth()};document.querySelector("#auth").onsubmit=auth}
async function auth(e){e.preventDefault();if(!sb){S.msg="Supabase configuration is missing in Vercel.";return renderAuth()}const f=new FormData(e.currentTarget),email=f.get("email"),password=f.get("password");
if(S.mode==="login"){const r=await sb.auth.signInWithPassword({email,password});if(r.error){S.msg=r.error.message;return renderAuth()}return load(r.data.user)}
const r=await sb.auth.signUp({email,password,options:{data:{full_name:f.get("full_name"),company_name:f.get("company_name")}}});if(r.error){S.msg=r.error.message;return renderAuth()}if(!r.data.session){S.msg="Account created. Check your email, then sign in.";return renderAuth()}load(r.data.user)}
async function load(user){S.user=user;const r=await sb.from("profiles").select("*,companies(*)").eq("id",user.id).maybeSingle();S.profile=r.data||null;S.company=r.data?.companies||null;renderDash()}
function shell(content){app.innerHTML=`<div class="shell"><aside><div class="brand">● YOUYOU</div><div class="tag">AI CUSTOMER AGENT</div><nav>${nav("overview","⌂","Overview")}${nav("conversations","◌","Conversations")}${nav("leads","✦","Leads")}${nav("knowledge","▤","Knowledge")}${nav("widget","◇","Website Widget")}${nav("ai","✧","AI Control Center")}${nav("settings","⚙","Settings")}</nav><div class="bottom"><b>PRO</b><button id="logout" class="ghost">Log out</button></div></aside><main>${content}</main></div>`;document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>{S.section=x.dataset.nav;renderDash()});document.querySelector("#logout").onclick=async()=>{await sb.auth.signOut();S.user=null;renderAuth()}}
function renderDash(){const company=S.company?.name||"Your workspace";const name=S.profile?.full_name||S.user?.email?.split("@")[0]||"there";let body="";
if(S.section==="knowledge")body=`<div class="card"><div class="head"><div><small>TRAINING</small><h2>Knowledge Base</h2></div><button id="add" class="primary">+ Add knowledge</button></div><p>Give YOUYOU the facts it needs to answer customers accurately.</p><div id="list">Loading…</div></div>`;
else if(S.section==="widget")body=`<div class="tw"><div class="card"><small>DEPLOYMENT</small><h2>Website Widget</h2><p>Add your AI agent to any website with one script.</p><pre>&lt;script src="https://YOUR-DOMAIN/widget.js"&gt;&lt;/script&gt;</pre><button id="copy" class="primary">Copy install code</button></div><div class="card"><small>PREVIEW</small><h2>Live assistant</h2><div class="chat"><i>Hi! I'm your YOUYOU AI agent.</i><b>How can I help?</b><i>Ask me about your products or services.</i></div></div></div>`;
else if(S.section==="ai")body=`<div class="card"><small>AI CONTROL CENTER</small><h2>Agent configuration</h2><div class="grid"><label>Agent name<input value="YOUYOU AI"></label><label>Tone<select><option>Professional</option><option>Friendly</option><option>Concise</option></select></label><label>Language<select><option>English</option><option>French</option><option>Arabic</option></select></label><label>Lead capture<select><option>Enabled</option><option>Disabled</option></select></label></div><button class="primary" onclick="alert('Configuration saved.')">Save configuration</button></div>`;
else if(S.section==="settings")body=`<div class="card"><small>WORKSPACE</small><h2>Settings</h2><div class="grid"><label>Company name<input id="cn" value="${esc(company)}"></label><label>Email<input disabled value="${esc(S.user.email)}"></label></div><button id="save" class="primary">Save changes</button></div>`;
else if(S.section==="conversations")body=`<div class="card empty"><h2>Conversations</h2><p>Your real customer conversations will appear here when the widget receives messages.</p></div>`;
else if(S.section==="leads")body=`<div class="card empty"><h2>Lead Inbox</h2><p>Qualified leads captured by YOUYOU will appear here.</p></div>`;
else body=`<div class="hero"><div><small>YOUYOU AI</small><h1>Your AI agent, ready to work.</h1><p>Turn website visitors into conversations, leads and customers.</p></div><button id="launch" class="primary">Launch agent</button></div><div class="cards"><div><small>CONVERSATIONS</small><strong>0</strong><p>Ready for your first visitor</p></div><div><small>LEADS</small><strong>0</strong><p>AI-qualified opportunities</p></div><div><small>KNOWLEDGE</small><strong>0</strong><p>Sources connected</p></div></div><div class="tw"><div class="card"><h2>Agent status <em>● LIVE</em></h2><p>Your workspace is connected to Supabase. Add knowledge and install the widget to start.</p></div><div class="card"><h2>${esc(company)}</h2><p>${esc(S.user.email)}</p></div></div>`;
shell(`<header><div><small>WORKSPACE</small><h2>${esc(company)}</h2></div><span>${esc(name)}</span></header>${body}`);
document.querySelector("#launch")?.addEventListener("click",()=>{S.section="widget";renderDash()});
document.querySelector("#copy")?.addEventListener("click",async()=>{await navigator.clipboard?.writeText('<script src="https://YOUR-DOMAIN/widget.js"></script>');alert("Copied.")});
document.querySelector("#add")?.addEventListener("click",addKnowledge);
document.querySelector("#save")?.addEventListener("click",async()=>{const name=document.querySelector("#cn").value;const r=await sb.from("companies").update({name}).eq("id",S.company.id);alert(r.error?.message||"Saved successfully.");if(!r.error)S.company.name=name});
if(S.section==="knowledge")loadKnowledge()}
async function loadKnowledge(){const list=document.querySelector("#list");const r=await sb.from("knowledge").select("*").eq("company_id",S.company.id).order("created_at",{ascending:false});if(r.error)return list.textContent=r.error.message;list.innerHTML=r.data.length?r.data.map(k=>`<article><b>${esc(k.title)}</b><p>${esc(k.content)}</p></article>`).join(""):"<p>No knowledge yet.</p>"}
async function addKnowledge(){const title=prompt("Knowledge title:");if(!title)return;const content=prompt("Business information:");if(!content)return;const r=await sb.from("knowledge").insert({company_id:S.company.id,title,content});if(r.error)alert(r.error.message);else loadKnowledge()}
async function boot(){if(!sb){S.msg="Supabase configuration is missing. Deploy this project through Vercel.";return renderAuth()}const r=await sb.auth.getSession();if(r.data.session)await load(r.data.session.user);else renderAuth();sb.auth.onAuthStateChange((_e,s)=>{if(!s){S.user=null;S.profile=null;S.company=null;renderAuth()}})}boot();