-- YOUYOU V7.1 — Landing Media Storage
-- Run ONCE in Supabase SQL Editor before testing permanent local video uploads.
-- This creates a public bucket for landing-page images/videos while keeping uploads
-- restricted to each authenticated user's own folder.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'landing-media',
  'landing-media',
  true,
  104857600,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/webm',
    'video/ogg',
    'video/quicktime',
    'video/x-m4v'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public landing pages need to load these assets without a signed session.
drop policy if exists "Public can read landing media" on storage.objects;
create policy "Public can read landing media"
on storage.objects
for select
to public
using (bucket_id = 'landing-media');

-- The first path segment is auth.uid(), generated by the YOUYOU builder.
drop policy if exists "Users can upload own landing media" on storage.objects;
create policy "Users can upload own landing media"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'landing-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can update own landing media" on storage.objects;
create policy "Users can update own landing media"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'landing-media'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'landing-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users can delete own landing media" on storage.objects;
create policy "Users can delete own landing media"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'landing-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);
